// <auto-generated />
using System;
using DentisAppAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace DentisAppAPI.Migrations
{
    [DbContext(typeof(DentisAppContext))]
    [Migration("20260720032857_NuevaMigracionCitas")]
    partial class NuevaMigracionCitas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DentisAppAPI.Models.Cita", b =>
                {
                    b.Property<int>("IdCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Relational:JsonPropertyName", "idCita");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCita"));

                    b.Property<string>("Estado")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasAnnotation("Relational:JsonPropertyName", "estado");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasAnnotation("Relational:JsonPropertyName", "fecha");

                    b.Property<int?>("IdOdontologo")
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Relational:JsonPropertyName", "idOdontologo");

                    b.Property<int?>("IdPaciente")
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Relational:JsonPropertyName", "idPaciente");

                    b.HasKey("IdCita")
                        .HasName("PK_DENTIS_CITA");

                    b.ToTable("CITAS", (string)null);
                });

            modelBuilder.Entity("DentisAppAPI.Models.CitaTratamiento", b =>
                {
                    b.Property<int?>("CitaId")
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Relational:JsonPropertyName", "idCita");

                    b.Property<int?>("TratamientoId")
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Relational:JsonPropertyName", "idTratamiento");

                    b.HasKey("CitaId", "TratamientoId");

                    b.HasIndex("TratamientoId");

                    b.ToTable("CITA_TRATAMIENTO", (string)null);
                });

            modelBuilder.Entity("DentisAppAPI.Models.Odontologo", b =>
                {
                    b.Property<int>("IdOdontologo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Relational:JsonPropertyName", "idOdontologo");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOdontologo"));

                    b.Property<string>("Correo")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasAnnotation("Relational:JsonPropertyName", "correo");

                    b.Property<string>("Especialidad")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasAnnotation("Relational:JsonPropertyName", "especialidad");

                    b.Property<string>("Estado")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasAnnotation("Relational:JsonPropertyName", "estado");

                    b.Property<string>("Nombre")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasAnnotation("Relational:JsonPropertyName", "nombre");

                    b.Property<string>("Telefono")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasAnnotation("Relational:JsonPropertyName", "telefono");

                    b.HasKey("IdOdontologo");

                    b.ToTable("ODONTOLOGOS", (string)null);
                });

            modelBuilder.Entity("DentisAppAPI.Models.Paciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Relational:JsonPropertyName", "idPaciente");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaciente"));

                    b.Property<string>("Apellido")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasAnnotation("Relational:JsonPropertyName", "apellido");

                    b.Property<string>("Cedula")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasAnnotation("Relational:JsonPropertyName", "cedula");

                    b.Property<string>("Correo")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasAnnotation("Relational:JsonPropertyName", "correo");

                    b.Property<string>("Direccion")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasAnnotation("Relational:JsonPropertyName", "direccion");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasAnnotation("Relational:JsonPropertyName", "fechaNacimiento");

                    b.Property<string>("Nombre")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasAnnotation("Relational:JsonPropertyName", "nombre");

                    b.Property<string>("Telefono")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasAnnotation("Relational:JsonPropertyName", "telefono");

                    b.HasKey("IdPaciente");

                    b.ToTable("PACIENTES", (string)null);
                });

            modelBuilder.Entity("DentisAppAPI.Models.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Relational:JsonPropertyName", "idPago");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasAnnotation("Relational:JsonPropertyName", "fechaPago");

                    b.Property<int?>("IdCita")
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Relational:JsonPropertyName", "idCita");

                    b.Property<string>("MetodoPago")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasAnnotation("Relational:JsonPropertyName", "metodoPago");

                    b.Property<decimal?>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "monto");

                    b.HasKey("IdPago");

                    b.ToTable("PAGOS", (string)null);
                });

            modelBuilder.Entity("DentisAppAPI.Models.Tratamiento", b =>
                {
                    b.Property<int>("IdTratamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Relational:JsonPropertyName", "idTratamiento");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTratamiento"));

                    b.Property<decimal?>("Costo")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "costo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasAnnotation("Relational:JsonPropertyName", "descripcion");

                    b.HasKey("IdTratamiento");

                    b.ToTable("TRATAMIENTOS", (string)null);
                });

            modelBuilder.Entity("DentisAppAPI.Models.CitaTratamiento", b =>
                {
                    b.HasOne("DentisAppAPI.Models.Cita", "Cita")
                        .WithMany("Tratamientos")
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DentisAppAPI.Models.Tratamiento", "Tratamiento")
                        .WithMany("Citas")
                        .HasForeignKey("TratamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("DentisAppAPI.Models.Cita", b =>
                {
                    b.Navigation("Tratamientos");
                });

            modelBuilder.Entity("DentisAppAPI.Models.Tratamiento", b =>
                {
                    b.Navigation("Citas");
                });
#pragma warning restore 612, 618
        }
    }
}
